#encoder/video_encoder.py

from typing import Optional
import pathlib
import struct
import subprocess
import os
import sys

_CREATE_NO_WINDOW = 0x08000000 if sys.platform == "win32" else 0

# ---------------------------------------------------------------------------
# GBA-native FPS values (tested and supported set).
# Maximum supported FPS is 14.9319
# ---------------------------------------------------------------------------
GBA_NATIVE_FPS = {
    1: 14.9319,
    2: 11.9455,
    3: 9.9546,
    4: 8.5325,
    5: 7.4659,
    6: 6.6364,
    7: 5.9727,
}

def nearest_gba_fps(fps: float) -> float:
    return min(GBA_NATIVE_FPS.values(), key=lambda x: abs(x - fps))

def nearest_gba_audio_rate(rate: int) -> int:
    return min(GBA_NATIVE_FPS.values(), key=lambda x: abs(x - rate))


def _compute_lookup_table_bins() -> dict:
    W, H, bw, bh, DW, ms, bpr = 240, 160, 2, 2, 240, 8, 30

    ct = bytearray()
    for i in range(-1024, 1024):
        v = 0 if i <= 0 else (255 if i >= 255 else i)
        ct.append((v >> 3) & 0xFF)

    bbo = bytearray()
    bpr_v = W // (bw * 2)
    bpc_v = H // (bh * 2)
    for idx in range(bpr_v * bpc_v):
        bx = idx % bpr_v;  by = idx // bpr_v
        bbo += struct.pack("<H", by * bh * 2 * DW + bx * bw * 2)

    zbo = bytearray()
    zbw = W // (bw * 2)
    for idx in range(W):
        bx = idx % zbw;  by = idx // zbw
        zbo += struct.pack("<H", by * bh * 2 * DW + bx * bw * 2)

    zmo = bytearray()
    for idx in range(DW):
        row = idx // bpr;  col = idx % bpr
        zmo += struct.pack("<H", row * ms * DW + col * ms)

    return {
        "clip_lookup_table":   bytes(ct),
        "big_block_offsets":   bytes(bbo),
        "zone_block_offsets":  bytes(zbo),
        "zone_motion_offsets": bytes(zmo),
    }


def write_lookup_table_bins(video_dir: pathlib.Path) -> dict:
    bins = _compute_lookup_table_bins()
    video_dir.mkdir(parents=True, exist_ok=True)
    for stem, data in bins.items():
        (video_dir / f"{stem}.bin").write_bytes(data)
    return bins


def write_header(path_h: pathlib.Path, frame_cnt: int, total_bytes: int,
                 codebook_size: int, output_fps: float):
    guard = "VIDEO_DATA_H"
    DECODER_BYTES_PER_BLOCK = 6

    video_dir = path_h.parent.parent.parent / "video"
    bins = write_lookup_table_bins(video_dir)

    n_big  = len(bins["big_block_offsets"])  // 2
    n_zone = len(bins["zone_block_offsets"]) // 2
    n_zmo  = len(bins["zone_motion_offsets"]) // 2

    lines = []
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append('#include "gba/gba.h"')
    lines.append("")
    lines.append(f"#define VIDEO_FRAME_COUNT              {frame_cnt}")
    lines.append( "#define VIDEO_WIDTH                    240")
    lines.append( "#define VIDEO_HEIGHT                   160")
    lines.append(f"#define VIDEO_TOTAL_BYTES              {total_bytes}")
    lines.append(f"#define VIDEO_FPS                      {int(round(output_fps * 10000))}")
    lines.append(f"#define UNIFIED_CODEBOOK_SIZE          {codebook_size}")
    lines.append( "#define EFFECTIVE_UNIFIED_CODEBOOK_SIZE 254")
    lines.append("")
    lines.append("// Frame type definitions")
    lines.append("#define FRAME_TYPE_I        0x00")
    lines.append("#define FRAME_TYPE_P        0x01")
    lines.append("")
    lines.append("// Special markers")
    lines.append("#define COLOR_BLOCK_MARKER  0xFF")
    lines.append("")
    lines.append("// Block parameters")
    lines.append("#define BLOCK_WIDTH         2")
    lines.append("#define BLOCK_HEIGHT        2")
    lines.append(f"#define BYTES_PER_BLOCK     {DECODER_BYTES_PER_BLOCK}")
    lines.append("")
    lines.append("// " + "-"*75)
    lines.append("// Precomputed lookup tables — ROM-resident binary data (video/*.bin).")
    lines.append("// Generated by the encoder, converted to .o by the Makefile bin2o rule.")
    lines.append("// Symbol names follow devkitARM bin2o convention: <filename>_bin[].")
    lines.append("//")
    lines.append(f"//   clip_lookup_table_bin  [2048 B] : YUV->RGB5 clip+shift  (u8,  center=index 1024)")
    lines.append(f"//   big_block_offsets_bin  [{len(bins['big_block_offsets']):4d} B] : pixel offset per 4x4 big block   ({n_big} x u16 LE)")
    lines.append(f"//   zone_block_offsets_bin [ {len(bins['zone_block_offsets']):3d} B] : pixel offset per zone big-block   ({n_zone} x u16 LE)")
    lines.append(f"//   zone_motion_offsets_bin[ {len(bins['zone_motion_offsets']):3d} B] : pixel offset per 8x8 motion block ({n_zmo} x u16 LE)")
    lines.append("// " + "-"*75)
    lines.append("")
    lines.append("// Raw byte symbols provided by bin2o")
    lines.append("extern const unsigned char clip_lookup_table_bin[];")
    lines.append("extern const unsigned char big_block_offsets_bin[];")
    lines.append("extern const unsigned char zone_block_offsets_bin[];")
    lines.append("extern const unsigned char zone_motion_offsets_bin[];")
    lines.append("")
    lines.append("// Typed pointer macros — cast from the raw bin2o byte symbol")
    lines.append("#define gClipLookupTable        ((const u8  *)clip_lookup_table_bin)")
    lines.append("#define gBigBlockOffsets        ((const u16 *)big_block_offsets_bin)")
    lines.append("#define gZoneBlockOffsets       ((const u16 *)zone_block_offsets_bin)")
    lines.append("#define gZoneMotionBlockOffsets ((const u16 *)zone_motion_offsets_bin)")
    lines.append("")
    lines.append("// Array size constants (number of elements, not bytes)")
    lines.append( "#define CLIP_LOOKUP_TABLE_SIZE       2048")
    lines.append(f"#define BIG_BLOCK_OFFSETS_COUNT      {n_big}")
    lines.append(f"#define ZONE_BLOCK_OFFSETS_COUNT     {n_zone}")
    lines.append(f"#define ZONE_MOTION_OFFSETS_COUNT    {n_zmo}")
    lines.append("")
    lines.append("// Video data and frame offset tables (also bin2o)")
    lines.append("extern const unsigned char video_data_bin[VIDEO_TOTAL_BYTES];")
    lines.append("extern const unsigned char frame_offsets_bin[VIDEO_FRAME_COUNT * 4];")
    lines.append("")
    lines.append("#define video_data    video_data_bin")
    lines.append("#define frame_offsets ((const unsigned int *)frame_offsets_bin)")
    lines.append("")
    lines.append(f"#endif // {guard}")
    lines.append("")

    path_h.write_text("\n".join(lines), encoding="utf-8")


def _write_binary(path: pathlib.Path, data: bytes):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("wb") as f:
        f.write(data)


def _write_int32_bin(path: pathlib.Path, values: list):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("wb") as f:
        for value in values:
            f.write(struct.pack("<I", value))


def write_source(path_bin: pathlib.Path, data: bytes, frame_offsets: list):
    _write_binary(path_bin, data)
    offsets_path = path_bin.with_name("frame_offsets.bin")
    _write_int32_bin(offsets_path, frame_offsets)

def _regen_standalone():
    import re as _re

    root = pathlib.Path(__file__).parent.parent
    header_path = root / "include" / "video" / "video_data.h"

    if not header_path.exists():
        print(f"❌ {header_path} not found — run the full encoder first.")
        return 1

    src = header_path.read_text(encoding="utf-8")

    def _get(name):
        m = _re.search(rf"#define\s+{name}\s+(\S+)", src)
        if not m:
            raise ValueError(f"Constant {name} not found in video_data.h")
        return m.group(1)

    frame_cnt   = int(_get("VIDEO_FRAME_COUNT"))
    total_bytes = int(_get("VIDEO_TOTAL_BYTES"))
    cb_size     = int(_get("UNIFIED_CODEBOOK_SIZE"))
    fps_raw     = int(_get("VIDEO_FPS"))
    output_fps  = fps_raw / 10000.0

    print(f"  frame_cnt={frame_cnt}, total_bytes={total_bytes}, "
          f"cb_size={cb_size}, fps={output_fps:.4f}")

    write_header(header_path, frame_cnt, total_bytes, cb_size, output_fps)
    print("✓ include/video/video_data.h regenerated")
    print("✓ video/*.bin lookup tables written")
    return 0


if __name__ == "__main__":
    raise SystemExit(_regen_standalone())


def _get_video_info(video_path: str) -> tuple:
    try:
        result = subprocess.run(
            ["ffprobe", "-v", "error", "-select_streams", "v:0",
             "-show_entries", "stream=width,height,r_frame_rate,duration",
             "-of", "csv=p=0", video_path],
            capture_output=True, text=True, check=True,
            creationflags=_CREATE_NO_WINDOW
        )
        parts = result.stdout.strip().split(",")
        w = int(parts[0])
        h = int(parts[1])
        num, den = parts[2].split("/")
        fps = float(num) / float(den)
        dur = float(parts[3]) if len(parts) > 3 else 0.0
        return fps, w, h, dur
    except Exception:
        return None, None, None, None


def _compute_letterbox_crop(src_w: int, src_h: int, dst_w: int = 240, dst_h: int = 160) -> dict:
    src_ratio = src_w / src_h
    dst_ratio = dst_w / dst_h

    if abs(src_ratio - dst_ratio) < 0.01:
        return {"vf": f"scale={dst_w}:{dst_h}"}

    if src_ratio > dst_ratio:
        scaled_w = dst_w
        scaled_h = int(dst_w / src_ratio)
        if scaled_h % 2 != 0:
            scaled_h -= 1
        pad_y = (dst_h - scaled_h) // 2
        vf = f"scale={scaled_w}:{scaled_h},pad={dst_w}:{dst_h}:0:{pad_y}:black"
    else:
        scaled_h = dst_h
        scaled_w = int(dst_h * src_ratio)
        if scaled_w % 2 != 0:
            scaled_w -= 1
        pad_x = (dst_w - scaled_w) // 2
        vf = f"scale={scaled_w}:{scaled_h},pad={dst_w}:{dst_h}:{pad_x}:0:black"

    return {"vf": vf}


def _transcode_to_temp(video_path: str, target_fps: float, duration: Optional[float],
                       full_duration: bool, tmp_dir: pathlib.Path,
                       src_w: int, src_h: int,
                       start_time: float = 0.0,
                       letterbox: bool = True,
                       crop: Optional[str] = None) -> str:
    tmp_video = str(tmp_dir / "input_resampled.mp4")

    vf_parts = []

    if crop:
        try:
            cx, cy, cw, ch = [int(v.strip()) for v in crop.split(",")]
            vf_parts.append(f"crop={cw}:{ch}:{cx}:{cy}")
            src_w, src_h = cw, ch
        except (ValueError, TypeError):
            pass

    if letterbox:
        lb = _compute_letterbox_crop(src_w, src_h)
        vf_parts.append(lb["vf"])
    else:
        vf_parts.append("scale=240:160")

    vf_parts.append(f"fps={target_fps:.6f}")

    vf = ",".join(vf_parts)

    from ffmpeg_utils import get_ffmpeg
    cmd = [get_ffmpeg(), "-y"]
    if start_time and start_time > 0:
        cmd.extend(["-ss", f"{start_time:.6f}"])
    cmd.extend(["-i", video_path])
    if not full_duration and duration is not None and duration > 0:
        cmd.extend(["-t", f"{duration:.6f}"])
    cmd.extend([
        "-vf", vf,
        "-c:v", "libx264", "-preset", "ultrafast", "-crf", "18",
        "-an",
        tmp_video
    ])

    label = f"{target_fps:.4f} fps, 240×160 ({'letterbox' if letterbox else 'stretch'})"
    if crop:
        label = f"crop({crop}) → {label}"
    print(f"  Pre-transcoding to {label}...")
    result = subprocess.run(cmd, capture_output=True, text=True,
                            creationflags=_CREATE_NO_WINDOW)
    if result.returncode != 0:
        print(f"  ⚠️  ffmpeg transcode failed: {result.stderr[-500:]}")
        return None
    return tmp_video


def extract_frames_from_video(video_path: str, duration: Optional[float], fps,
                               full_duration: bool = False, dither: bool = False,
                               start_time: float = 0.0,
                               letterbox: bool = True,
                               crop: Optional[str] = None):
    import cv2
    import numpy as np
    from core_encoder import pack_yuv444_frame
    from dither_opt import apply_dither_optimized

    src_fps, src_w, src_h, src_dur = _get_video_info(video_path)
    if src_fps is None:
        cap_probe = cv2.VideoCapture(video_path)
        src_fps = cap_probe.get(cv2.CAP_PROP_FPS) or 24.0
        src_w   = int(cap_probe.get(cv2.CAP_PROP_FRAME_WIDTH))
        src_h   = int(cap_probe.get(cv2.CAP_PROP_FRAME_HEIGHT))
        src_dur = cap_probe.get(cv2.CAP_PROP_FRAME_COUNT) / src_fps
        cap_probe.release()

    if fps is None:
        target_fps = nearest_gba_fps(src_fps)
    else:
        target_fps = nearest_gba_fps(float(fps))

    print(f"Source: {src_fps:.4f} fps, {src_w}×{src_h}")
    print(f"Target: {target_fps:.4f} fps (GBA-native), 240×160")

    script_dir = pathlib.Path(__file__).parent.parent
    tmp_dir = script_dir / "temp"
    if tmp_dir.exists():
        import shutil
        shutil.rmtree(str(tmp_dir), ignore_errors=True)
        print("🧹 Cleaned previous temp files")
    tmp_dir.mkdir(exist_ok=True)

    tmp_video = _transcode_to_temp(video_path, target_fps, duration,
                                   full_duration, tmp_dir, src_w, src_h,
                                   start_time=start_time,
                                   letterbox=letterbox,
                                   crop=crop)
    if tmp_video is None:
        tmp_video = video_path
        print("  ⚠️  Using original video without pre-transcoding")

    cap = cv2.VideoCapture(tmp_video)
    if not cap.isOpened():
        raise SystemExit(f"❌ Cannot open transcoded video: {tmp_video}")

    actual_fps = cap.get(cv2.CAP_PROP_FPS) or target_fps
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    if full_duration or duration is None:
        grab_max = total_frames
        print(f"Encoding full video: {total_frames} frames at {actual_fps:.4f} fps ({total_frames/actual_fps:.2f}s)")
    else:
        grab_max = total_frames
        print(f"Encoding {duration:.3f}s: {grab_max} frames at {actual_fps:.4f} fps")

    if dither:
        print("🎨 Dithering enabled (serpentine Floyd-Steinberg)")

    mmap_path = tmp_dir / "frames.mmap"
    BLOCKS_H, BLOCKS_W, BPB = 80, 120, 12
    expected = max(1, grab_max)
    mmap = np.memmap(str(mmap_path), dtype=np.uint8, mode='w+',
                     shape=(expected, BLOCKS_H, BLOCKS_W, BPB))

    frame_count = 0
    print("Extracting frames...", flush=True)

    for idx in range(grab_max):
        ret, frm = cap.read()
        if not ret:
            break
        if frm.shape[1] != 240 or frm.shape[0] != 160:
            frm = cv2.resize(frm, (240, 160), cv2.INTER_AREA)
        frm = cv2.GaussianBlur(frm, (3, 3), 0.41)
        if dither:
            frm = apply_dither_optimized(frm)
        frame_blocks = pack_yuv444_frame(frm)
        if frame_count < expected:
            mmap[frame_count] = frame_blocks
            frame_count += 1
        pct = min(frame_count / expected, 1.0)
        filled = int(30 * pct)
        bar = "█" * filled + "░" * (30 - filled)
        print(f"\r  [{bar}] {pct*100:5.1f}%  {frame_count}/{expected} frames",
              end="", flush=True)

    cap.release()
    print()

    if frame_count == 0:
        raise SystemExit("❌ No frames were sampled")

    mmap.flush()
    del mmap

    frames_mmap = np.memmap(str(mmap_path), dtype=np.uint8, mode='r',
                            shape=(frame_count, BLOCKS_H, BLOCKS_W, BPB))

    print(f"Total frames extracted: {frame_count}  ({frame_count/target_fps:.2f}s @ {target_fps:.4f} fps)", flush=True)
    print(f"Frames saved to: {mmap_path}")
    return frames_mmap, target_fps, str(mmap_path)


_GBA_BUTTON_BITMASKS = {
    "A":      0x0001,
    "B":      0x0002,
    "Select": 0x0004,
    "Start":  0x0008,
    "R":      0x0010,
    "L":      0x0020,
}

_GBA_BUTTON_NAMES = {
    0x0001: "A_BUTTON",
    0x0002: "B_BUTTON",
    0x0004: "SELECT_BUTTON",
    0x0008: "START_BUTTON",
    0x0010: "R_BUTTON",
    0x0020: "L_BUTTON",
}


def buttons_to_skip_key(button_list: list) -> int:
    mask = 0
    for name in (button_list or []):
        mask |= _GBA_BUTTON_BITMASKS.get(name, 0)
    return mask


def skip_key_to_c_expr(mask: int) -> str:
    if mask == 0:
        return "0  /* skip disabled */"
    parts = [name for bit, name in sorted(_GBA_BUTTON_NAMES.items()) if mask & bit]
    expr = " | ".join(parts)
    if len(parts) > 1:
        return f"({expr})"
    return expr


def write_decoproject_header(
    path_h: pathlib.Path,
    frame_cnt: int,
    total_bytes: int,
    codebook_size: int,
    output_fps: float,
    audio_format: str = "pcm",
    sample_rate: int = 18157,
    adpcm_timer_reload: int = 0,
    adpcm_spf: int = 0,
    audio_duration_ms: int = 0,
    audio_data_len: int = 0,
    frame_audio_count: int = 0,
    skip_key: int = 0x0001,
    no_audio: bool = False,
):
    guard   = "GUARD_VIDEO_H"
    if no_audio:
        fmt_val = 2
    elif audio_format == "adpcm":
        fmt_val = 1
    else:
        fmt_val = 0
    fps_raw = int(round(output_fps * 10000))

    lines = []
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append("// Generated by GBA Video Studio — do not edit manually.")
    lines.append("// Re-run the encoder to regenerate.")
    lines.append("")
    lines.append('#include "global.h"')
    lines.append("")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// Video parameters")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append(f"#define VIDEO_FRAME_COUNT        {frame_cnt}")
    lines.append( "#define VIDEO_DISPLAY_WIDTH      240")
    lines.append( "#define VIDEO_DISPLAY_HEIGHT     160")
    lines.append(f"#define VIDEO_TOTAL_BYTES        {total_bytes}")
    lines.append(f"#define VIDEO_FPS_RAW            {fps_raw}  // fps * 10000")
    lines.append(f"#define VIDEO_CODEBOOK_SIZE      {codebook_size}")
    lines.append( "#define VIDEO_EFFECTIVE_CODEBOOK 254  // 0xFF reserved as marker")
    lines.append("")
    lines.append("// Frame type identifiers")
    lines.append("#define VIDEO_FRAME_TYPE_I        0x00")
    lines.append("#define VIDEO_FRAME_TYPE_P        0x01")
    lines.append("#define VIDEO_COLOR_BLOCK_MARKER  0xFF")
    lines.append("")
    lines.append("// Block geometry (2x2 sub-block, 4x4 macroblock)")
    lines.append("#define VIDEO_BLOCK_W             2")
    lines.append("#define VIDEO_BLOCK_H             2")
    lines.append("#define VIDEO_BYTES_PER_BLOCK     6  // YUV420: 4Y + 1Cb + 1Cr")
    lines.append("#define VIDEO_ZONE_HEIGHT         16  // pixel rows per zone")
    lines.append("")
    lines.append("// Motion compensation")
    lines.append("#define VIDEO_MOTION_RANGE        7")
    lines.append("#define VIDEO_MOTION_BLOCK_SIZE   8")
    lines.append("")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// Audio parameters")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append(f"#define VIDEO_AUDIO_FORMAT       {fmt_val}  // 0=PCM 8-bit, 1=ADPCM 4-bit, 2=no audio")
    if not no_audio:
        lines.append(f"#define VIDEO_SAMPLE_RATE        {sample_rate}")
        if fmt_val == 1:
            lines.append(f"#define VIDEO_ADPCM_TIMER_RELOAD {adpcm_timer_reload}")
            lines.append(f"#define VIDEO_ADPCM_SPF          {adpcm_spf}  // samples per frame")
        lines.append(f"#define VIDEO_AUDIO_DURATION_MS  {audio_duration_ms}")
        lines.append(f"#define VIDEO_AUDIO_DATA_LEN     {audio_data_len}")
        if frame_audio_count > 0:
            lines.append(f"#define VIDEO_FRAME_AUDIO_COUNT  {frame_audio_count}")
    lines.append("")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// Skip key — press this button (or combination) during playback to skip.")
    lines.append("// Uses GBA button bitmasks. Set to 0 to disable skipping.")
    lines.append("// Override before including this header: #define VIDEO_SKIP_KEY  B_BUTTON")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("#ifndef VIDEO_SKIP_KEY")
    skip_expr = skip_key_to_c_expr(skip_key)
    lines.append(f"#define VIDEO_SKIP_KEY  {skip_expr}")
    lines.append("#endif")
    lines.append("")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("// Public API")
    lines.append("// ---------------------------------------------------------------------------")
    lines.append("")
    lines.append("// Create the video player task. Returns the new task ID.")
    lines.append("// Call after ResetTasks() so no other tasks interfere.")
    lines.append("u8    VideoPlayer_Start(void);")
    lines.append("")
    lines.append("// Returns TRUE once playback has finished and the task has destroyed itself.")
    lines.append("// Poll this from a watcher task to detect completion.")
    lines.append("bool8 VideoPlayer_IsDone(void);")
    lines.append("")
    lines.append("// Immediately stop playback and restore hardware state.")
    lines.append("// Only valid while VideoPlayer_IsDone() == FALSE.")
    lines.append("void  VideoPlayer_ForceStop(void);")
    lines.append("")
    lines.append(f"#endif // {guard}")
    lines.append("")

    path_h.parent.mkdir(parents=True, exist_ok=True)
    path_h.write_text("\n".join(lines), encoding="utf-8")


def copy_decoproject_output(
    project_root: pathlib.Path,
    video_bin_dir: pathlib.Path,
    include_video_dir: pathlib.Path,
    audio_format: str,
    frame_cnt: int,
    total_bytes: int,
    codebook_size: int,
    output_fps: float,
    sample_rate: int = 18157,
    adpcm_timer_reload: int = 0,
    adpcm_spf: int = 0,
    audio_duration_ms: int = 0,
    audio_data_len: int = 0,
    frame_audio_count: int = 0,
    skip_key: int = 0x0001,
    no_audio: bool = False,
):
    import shutil

    out_root    = project_root / "output"
    out_gfx     = out_root / "graphics" / "video"
    out_include = out_root / "include"
    out_src     = out_root / "src"

    out_gfx.mkdir(parents=True, exist_ok=True)
    out_include.mkdir(parents=True, exist_ok=True)
    out_src.mkdir(parents=True, exist_ok=True)

    bins_to_copy = [
        "video_data.bin",
        "frame_offsets.bin",
        "clip_lookup_table.bin",
        "big_block_offsets.bin",
        "zone_block_offsets.bin",
        "zone_motion_offsets.bin",
        "audio_data.bin",
        "frame_audio_offsets.bin",
        "i_frame_audio_offsets.bin",
    ]
    for name in bins_to_copy:
        src = video_bin_dir / name
        if src.exists():
            shutil.copy2(str(src), str(out_gfx / name))

    lookup_bins = [
        "clip_lookup_table.bin",
        "big_block_offsets.bin",
        "zone_block_offsets.bin",
        "zone_motion_offsets.bin",
    ]
    for name in lookup_bins:
        src = project_root / "video" / name
        if src.exists():
            shutil.copy2(str(src), str(out_gfx / name))

    write_decoproject_header(
        path_h            = out_include / "video.h",
        frame_cnt         = frame_cnt,
        total_bytes       = total_bytes,
        codebook_size     = codebook_size,
        output_fps        = output_fps,
        audio_format      = audio_format,
        sample_rate       = sample_rate,
        adpcm_timer_reload= adpcm_timer_reload,
        adpcm_spf         = adpcm_spf,
        audio_duration_ms = audio_duration_ms,
        audio_data_len    = audio_data_len,
        frame_audio_count = frame_audio_count,
        skip_key          = skip_key,
        no_audio          = no_audio,
    )

    if no_audio:
        stub_content = (
            "#ifndef AUDIO_DATA_H\n#define AUDIO_DATA_H\n\n"
            "// No audio — generated stub.\n"
            "#define AUDIO_FORMAT 2\n"
            "#define audio_data_len 0\n"
            "#define SAMPLE_RATE 0\n"
            "#define AUDIO_BYTES_PER_SECOND 0\n"
            "#define ADPCM_TIMER_RELOAD 0\n"
            "#define ADPCM_SAMPLES_PER_FRAME 0\n"
            "#define AUDIO_DURATION_MS 0\n"
            "#define I_FRAME_AUDIO_OFFSET_COUNT 0\n"
            "\n#endif // AUDIO_DATA_H\n"
        )
        for dest_dir in (include_video_dir, out_include):
            dest_dir.mkdir(parents=True, exist_ok=True)
            (dest_dir / "audio_data.h").write_text(stub_content, encoding="utf-8")

    encoder_dir  = pathlib.Path(__file__).parent
    project_root = encoder_dir.parent
    for src_file, dst in [
        (encoder_dir  / "video.c",       out_src  / "video.c"),
        (project_root / "INTEGRATION.md", out_root / "INTEGRATION.md"),
    ]:
        if src_file.exists():
            shutil.copy2(str(src_file), str(dst))
        else:
            print(f"⚠  {src_file.name} not found — skipping.")

    print(f"✓ decompilation project output: {out_root}")
