#ifndef ADPCM_DECODER_H
#define ADPCM_DECODER_H

#include "gba/types.h"
#include "audio_data.h"
#include "video_data.h"

#if AUDIO_FORMAT == 1

// HALF_BUF = samples per video frame for the encoded sample rate.
// This value is generated by the encoder in audio_data.h as ADPCM_SAMPLES_PER_FRAME.
// It is the exact integer count of Timer 0 overflows per GBA video frame,
// which only exists for "nice rates" where the Timer 0 reload divides 280896
// (GBA cycles per frame) exactly. This guarantees zero accumulated sync error
// between audio and video over the entire clip.
//
// The encoder automatically snaps the requested sample rate to the nearest
// nice rate and writes ADPCM_SAMPLES_PER_FRAME into audio_data.h.
#define HALF_BUF    ADPCM_SAMPLES_PER_FRAME

extern s8  gMixBuf[2][HALF_BUF];  // double buffer
extern u32 gPlayBuf;               // index of the buffer currently played by DMA
extern u32 gAdpcmOffset;

// Non-critical function (ROM/EWRAM)
void AdpcmDecoder_seek(u32 offset);

// Critical IWRAM functions — require long_call when called from ROM
void AdpcmDecoder_decodeBlock(s8 *dst)  __attribute__((long_call));
void AdpcmDecoder_timer1_isr(void)      __attribute__((long_call));

#endif
#endif // ADPCM_DECODER_H
