// video_decoder.c
// Non-hot-path decoder functions: codebook loading, public accessors.
// Hot-path decode functions are in video_decoder_render.c (ROM, no IWRAM).
//
// Memory layout changes vs original:
//   - gClipLookupTable / gClipLookupTableRaw : ROM (precalculated by encoder, in video_data.h)
//   - gBigBlockOffsets / gZoneBlockOffsets / gZoneMotionBlockOffsets : ROM (idem)
//   - sRgb555Buf[2]  : EWRAM  (4096 B — write-only from decode path)
//   - sCodebookRaw   : EWRAM  (1540 B — write-only from DMA + byte copy)

#include "gba/gba.h"
#include <string.h>
#include "gba_video.h"
#include "video_decoder.h"

// ---------------------------------------------------------------------------
// Decoder state — non-static so video_decoder_render.c can access them
// ---------------------------------------------------------------------------

// Codebook buffers in EWRAM — written at I-frame decode, not performance-critical
EWRAM_DATA u8       sCodebookRaw[UNIFIED_CODEBOOK_SIZE * sizeof(YuvBlock) + 4]
                        __attribute__((aligned(32)));
YuvBlock *sCodebook = NULL;

bool8 sCodebookLoaded = FALSE;
s32   sLastCheckFrame = -1;
s32   sNextIFrame     = -1;

// Double-buffered RGB555 codebook in EWRAM — swapped once per I-frame
EWRAM_DATA Rgb555Block sRgb555Buf[2][UNIFIED_CODEBOOK_SIZE];
s32          sRgb555Idx      = 1;
Rgb555Block *sRgb555Codebook = NULL;
bool8        sRgb555Loaded   = FALSE;

// ---------------------------------------------------------------------------
// ROM lookup tables — declared via #define macros in video_data.h.
// Symbols are bin2o-generated from video/*.bin files:
//   gClipLookupTable        → clip_lookup_table_bin
//   gBigBlockOffsets        → big_block_offsets_bin
//   gZoneBlockOffsets       → zone_block_offsets_bin
//   gZoneMotionBlockOffsets → zone_motion_offsets_bin
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Public accessors
// ---------------------------------------------------------------------------

bool8 VideoDecoder_is_codebook_preloaded(void)        { return sCodebookLoaded; }
bool8 VideoDecoder_is_rgb555_codebook_preloaded(void) { return sRgb555Loaded; }
s32   VideoDecoder_get_next_i_frame(void)              { return sNextIFrame; }

void VideoDecoder_reset_codebook(void) {
    sCodebookLoaded = FALSE;
    sRgb555Loaded   = FALSE;
    sLastCheckFrame = -1;
    sNextIFrame     = -1;
}

// ---------------------------------------------------------------------------
// Init: tables are precomputed in ROM — just set up the codebook pointer.
// ---------------------------------------------------------------------------
void VideoDecoder_init(void) {
    // All lookup tables (gClipLookupTable, gBigBlockOffsets, gZoneBlockOffsets,
    // gZoneMotionBlockOffsets) are now const arrays in ROM generated by the
    // encoder — no runtime computation needed.
    sRgb555Codebook = sRgb555Buf[sRgb555Idx];
}

// ---------------------------------------------------------------------------
// Codebook copy (alignment-safe, DMA for bulk transfer)
// ---------------------------------------------------------------------------
void CopyCodebook(u8 *dstRaw, const u8 *src, YuvBlock **outPtr, s32 size) {
    u8 *dst = dstRaw + 4;
    *outPtr = (YuvBlock *)dst;
    s32 remain = size * BYTES_PER_BLOCK;

    if ((u32)src & 1) {
        u8 d = *src++;
        dst[-1] = dst[-3] = d;
        *outPtr = (YuvBlock *)((u32)*outPtr - 1);
        remain--;
    }
    if ((u32)src & 2) {
        dst[-2] = *src++;
        dst[-1] = *src++;
        *outPtr = (YuvBlock *)((u32)*outPtr - 2);
        remain -= 2;
    }

    DmaCopy32(3, src, dst, remain & ~3);
    s32 tail = remain & 3;
    src += remain - tail;
    dst += remain - tail;
    while (tail--) *dst++ = *src++;
}

// ---------------------------------------------------------------------------
// YUV -> RGB555 codebook conversion
// Uses gClipLookupTable from ROM (center offset 1024 baked in at generation).
// ---------------------------------------------------------------------------
void ConvertYuvToRgb555(const YuvBlock *yuv, Rgb555Block *rgb, s32 size) {
    // gClipLookupTable[0] corresponds to input index -1024.
    // Access as lut[1024 + value] — equivalent to old lut[value] with the
    // centered raw array.
    const u8 *lut = gClipLookupTable + 1024;
    s32 i, y, x;
    for (i = 0; i < size; i++) {
        s8 cb = yuv[i].cb;
        s8 cr = yuv[i].cr;
        s32 dR =  (cr << 1);
        s32 dG =  (cb >> 1) + cr;
        s32 dB =  (cb << 1);
        for (y = 0; y < 2; y++) {
            for (x = 0; x < 2; x++) {
                u8  yv = yuv[i].y[y][x];
                u16 r  = lut[yv + dR];
                u16 g  = lut[yv - dG];
                u16 b  = lut[yv + dB];
                rgb[i].row[y].u16_vals[x] = r | (g << 5) | (b << 10);
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Public API: codebook loading (called from video_decoder_render.c — ROM→ROM)
// ---------------------------------------------------------------------------
void VideoDecoder_load_codebook_and_convert(const u8 *src) {
    if (!sCodebookLoaded)
        CopyCodebook(sCodebookRaw, src, &sCodebook, UNIFIED_CODEBOOK_SIZE);
    if (!sRgb555Loaded)
        ConvertYuvToRgb555(sCodebook,
                           sRgb555Buf[sRgb555Idx ^ 1],
                           UNIFIED_CODEBOOK_SIZE);
}

void VideoDecoder_preload_codebook(const u8 *src) {
    u8 type = src[0];
    if (type != FRAME_TYPE_I || sRgb555Loaded) {
        VBlankIntrWait();
        return;
    }
    if (!sCodebookLoaded) {
        CopyCodebook(sCodebookRaw, src + 1, &sCodebook, UNIFIED_CODEBOOK_SIZE);
        sCodebookLoaded = TRUE;
        return;
    }
    if (!sRgb555Loaded) {
        ConvertYuvToRgb555(sCodebook,
                           sRgb555Buf[sRgb555Idx ^ 1],
                           UNIFIED_CODEBOOK_SIZE);
        sRgb555Loaded = TRUE;
    }
}

void VideoDecoder_preload_codebook_blocking(const u8 *src) {
    // Calls preload_codebook repeatedly until the RGB555 codebook is fully ready.
    // Requires exactly 2 calls:
    //   1st: copies YUV codebook (sCodebookLoaded = TRUE)
    //   2nd: converts YUV → RGB555 (sRgb555Loaded = TRUE)
    // Each call does VBlankIntrWait() internally, blocking ~2 VBlanks (~33ms) — acceptable on seek.
    while (!VideoDecoder_is_rgb555_codebook_preloaded())
        VideoDecoder_preload_codebook(src);
}

void VideoDecoder_find_next_i_frame(const u8 *videoData, s32 startFrame) {
    const s32 kMaxSearch = 30;
    if (sLastCheckFrame == -1)
        sLastCheckFrame = startFrame;
    s32 i;
    for (i = 0; i < kMaxSearch; i++) {
        if (VideoDecoder_is_i_frame(videoData + frame_offsets[sLastCheckFrame])) {
            sNextIFrame     = sLastCheckFrame;
            sLastCheckFrame = -1;
            return;
        }
        sLastCheckFrame++;
    }
}
